nom : Projet Java d'analyse CRDA
sur :
  pousser :
  pull_request :

emplois :
  scanner :
    name : Analyser le projet Java
    fonctionne sur : ubuntu-latest

    étapes :
      - nom : Projet de paiement
        utilise : actions/checkout@v2

      - nom : Install CRDA cli
        utilise : redhat-actions/openshift-tools-installer@v1
        avec :
          source : github
          crda : latest

      - nom : Configuration Java
        utilise : actions/setup-java@v2
        avec :
          distribution : temurin
          version java : 11
      
      - nom : CRDA Scanner et télécharger SARIF
        identifiant : analyse
        utilise : redhat-actions/crda@v1
        avec :
          snyk_token : ${{ secrets.SNYK_TOKEN }}
        erreur continue : true  

      - nom : Imprimer le lien du rapport
        exécuter : echo ${{ étapes.scan.outputs.report_link }}
